<?php include("header.php"); ?>
<section class="section page-section pb-5 animTop">
    <div class="page-hero" style="background-image: url(images-tpm/membership-hero.jpg);"></div>
    <div class="container pt-5">
        <div class="title clearfix">
             <h1>Terms & Conditions</h1>
        </div>
        <div class="content">
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic nostrum, placeat corrupti, aliquam expedita repellendus reprehenderit dolore laborum quia natus animi? Illo amet harum molestiae culpa perferendis mollitia quo quas?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem expedita, incidunt facere reiciendis ad beatae! Praesentium facere repellat debitis ipsa adipisci, nostrum officia, libero molestiae saepe eos, similique illum rerum quis quaerat cumque sequi odio porro earum ullam eligendi iusto inventore dolore! Obcaecati numquam nobis officia unde non ad, laborum praesentium ex odit ab. Ad vel dolorem rem sunt, maxime numquam nemo necessitatibus distinctio ut eveniet quas quis asperiores neque exercitationem ipsum dicta tempora. Obcaecati veritatis consequuntur dolorum perferendis tenetur cumque fuga. Sapiente dicta, enim officia nisi veniam ullam expedita impedit. Libero ullam reprehenderit itaque sit blanditiis a obcaecati eos.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic nostrum, placeat corrupti, aliquam expedita repellendus reprehenderit dolore laborum quia natus animi? Illo amet harum molestiae culpa perferendis mollitia quo quas?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem expedita, incidunt facere reiciendis ad beatae! Praesentium facere repellat debitis ipsa adipisci, nostrum officia, libero molestiae saepe eos, similique illum rerum quis quaerat cumque sequi odio porro earum ullam eligendi iusto inventore dolore! Obcaecati numquam nobis officia unde non ad, laborum praesentium ex odit ab. Ad vel dolorem rem sunt, maxime numquam nemo necessitatibus distinctio ut eveniet quas quis asperiores neque exercitationem ipsum dicta tempora. Obcaecati veritatis consequuntur dolorum perferendis tenetur cumque fuga. Sapiente dicta, enim officia nisi veniam ullam expedita impedit. Libero ullam reprehenderit itaque sit blanditiis a obcaecati eos.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic nostrum, placeat corrupti, aliquam expedita repellendus reprehenderit dolore laborum quia natus animi? Illo amet harum molestiae culpa perferendis mollitia quo quas?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem expedita, incidunt facere reiciendis ad beatae! Praesentium facere repellat debitis ipsa adipisci, nostrum officia, libero molestiae saepe eos, similique illum rerum quis quaerat cumque sequi odio porro earum ullam eligendi iusto inventore dolore! Obcaecati numquam nobis officia unde non ad, laborum praesentium ex odit ab. Ad vel dolorem rem sunt, maxime numquam nemo necessitatibus distinctio ut eveniet quas quis asperiores neque exercitationem ipsum dicta tempora. Obcaecati veritatis consequuntur dolorum perferendis tenetur cumque fuga. Sapiente dicta, enim officia nisi veniam ullam expedita impedit. Libero ullam reprehenderit itaque sit blanditiis a obcaecati eos.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic nostrum, placeat corrupti, aliquam expedita repellendus reprehenderit dolore laborum quia natus animi? Illo amet harum molestiae culpa perferendis mollitia quo quas?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem expedita, incidunt facere reiciendis ad beatae! Praesentium facere repellat debitis ipsa adipisci, nostrum officia, libero molestiae saepe eos, similique illum rerum quis quaerat cumque sequi odio porro earum ullam eligendi iusto inventore dolore! Obcaecati numquam nobis officia unde non ad, laborum praesentium ex odit ab. Ad vel dolorem rem sunt, maxime numquam nemo necessitatibus distinctio ut eveniet quas quis asperiores neque exercitationem ipsum dicta tempora. Obcaecati veritatis consequuntur dolorum perferendis tenetur cumque fuga. Sapiente dicta, enim officia nisi veniam ullam expedita impedit. Libero ullam reprehenderit itaque sit blanditiis a obcaecati eos.</p>
        </div>
    </div>
   
</section>
<?php include("footer.php");?>